// <auto-generated />
using System;
using ICM.Crypto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICM.Crypto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    [Migration("20251209141712_CreateBlockchainSnapshotsTable")]
    partial class CreateBlockchainSnapshotsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICM.Crypto.Infrastructure.Persistence.Entities.BlockchainSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Blockchain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RawJson")
                        .HasDatabaseName("ix_snapshots_rawjson_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RawJson"), "gin");

                    b.HasIndex("Blockchain", "CreatedAtUtc")
                        .HasDatabaseName("ix_snapshots_blockchain_createdat");

                    b.ToTable("blockchain_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
