// <auto-generated />
using System;
using ICM.Crypto.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ICM.Crypto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    partial class CryptoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ICM.Crypto.Infrastructure.Persistence.Entities.BlockchainSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Blockchain")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ChainKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Network")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RawJson")
                        .HasDatabaseName("ix_snapshots_rawjson_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RawJson"), "gin");

                    b.HasIndex("ChainKey", "CreatedAtUtc")
                        .HasDatabaseName("ix_snapshots_chain_createdat");

                    b.ToTable("blockchain_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("chk_snapshots_duration", "\"DurationMs\" >= 0");

                            t.HasCheckConstraint("chk_snapshots_httpstatus", "\"HttpStatus\" >= 100 AND \"HttpStatus\" <= 599");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
