<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <AssemblyName>ICM.Crypto.Infrastructure.Http</AssemblyName>
        <RootNamespace>ICM.Crypto.Infrastructure.Http</RootNamespace>
    </PropertyGroup>

</Project>
