<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL"/>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="NUnit"/>
        <PackageReference Include="NUnit.Analyzers"/>
        <PackageReference Include="NUnit3TestAdapter"/>
        <PackageReference Include="Testcontainers" />
        <PackageReference Include="Testcontainers.PostgreSql" />
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\ICM.Crypto.Infrastructure.Persistence\ICM.Crypto.Infrastructure.Persistence.csproj" />
    </ItemGroup>

</Project>
