# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: ICMCrypto-CI

on:
  push:
    branches: ["main", "development"]
  pull_request:
    branches: ["main", "development"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Web API image (integration)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/ICM.Crypto.WebApi/Dockerfile
          tags: icm/blockchain/api:integration
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Restore dependencies
        run: dotnet restore

      - name: Build [Debug]
        run: dotnet build --no-restore --configuration Debug
      
      - name: Build [Release]
        run: dotnet build --no-restore --configuration Release
      
      - name: Run Unit Tests [Release]
        run: dotnet test tests/ICM.Crypto.UnitTests/ICM.Crypto.UnitTests.csproj --no-build --configuration Release --verbosity normal

      - name: Run Integration Tests [Release]
        run: dotnet test tests/ICM.Crypto.IntegrationTests/ICM.Crypto.IntegrationTests.csproj --no-build --configuration Release --verbosity normal

      - name: Run Functional Tests [Release]
        run: dotnet test tests/ICM.Crypto.FunctionalTests/ICM.Crypto.FunctionalTests.csproj --no-build --configuration Release --verbosity normal
